sudo: false
language: go
go:
  - 1.11.x
  - 1.12.x
env:
  - GO111MODULE=on
git:
  depth: 1
notifications:
  email: false
before_script:
  - go install -mod vendor github.com/golangci/golangci-lint/cmd/golangci-lint
script:
  - golangci-lint run
  - go test -v ./...
