sudo: false
language: go
go:
  - 1.13.x
os:
  - linux
  - osx
cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod
env:
  - GO111MODULE=on
git:
  depth: 1
notifications:
  email: false
before_script:
  - curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.23.2
script:
  - golangci-lint run
  - go test -v ./...
