name: Go
on: 
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master
jobs:
  test:
    name: Test
    strategy:
      matrix:
        golang: ["1.13", "1.12"]
        os: ["ubuntu-latest", "macos-latest"]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Set up Go ${{ matrix.golang }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.golang }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Lint
      run: golangci-lint run
    
    - name: Test
      run: go test -v ./...
